# Generated by Django 3.2.9 on 2021-11-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20211128_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('listing', models.ManyToManyField(blank=True, related_name='category_listings', to='auctions.Listing')),
            ],
        ),
    ]
