# Generated by Django 3.2.9 on 2021-11-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
