# Generated by Django 3.2.9 on 2021-11-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20211129_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='starting',
            field=models.IntegerField(),
        ),
    ]
