# Generated by Django 3.2.9 on 2021-11-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FD', 'food'), ('CL', 'clothes'), ('TO', 'tools'), ('OT', 'others')], max_length=3),
        ),
    ]
