# Generated by Django 3.2.9 on 2021-11-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('food', 'food'), ('clothes', 'clothes'), ('tools', 'tools'), ('others', 'others')], max_length=7),
        ),
    ]
